# Use postgres/example user/password credentials
version: '3.9'

services:

  merchandise-api-db:
    build: .
    container_name: postgres_merchandise_api
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5001:5432"
    volumes:
      - merchandise-api-db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  user-api-db:
    build: .
    container_name: postgres_user_api
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5002:5432"
    volumes:
      - user-api-db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  merchandise-api-db-store:
  user-api-db-store:
